### ISSUE TITLE
Is it possible to have more than one on a page?

### ISSUE THREAD

**Issue by NetOpWibby** [agrimsrud/svgPieTimer.js#2]
Hi there!

I am currently in the process of jQuer-ifying this nifty plugin, and I need to have several on a page (tiny ones, I'm not an animal). I'm going to continue searching for a solution in the meantime, but if anyone has ideas on how to proceed, I'd greatly appreciate it!

**Comment by NetOpWibby** [comment]
Haha, I figured it out! I made my first jQuery plugin in the process, as well. I'll append this comment with a link to my repo once I clean it up.

**Comment by agrimsrud** [comment]
Hey Paul! Not at my desk at the moment, but glad you figured it out. I'm excited to see your plugin! 😄
